import"server-only";import{getDatabaseClient}from"@/platform/database/client";import type{HousekeepingSnapshot}from"./contracts";import type{HousekeepingAction}from"./schemas";type Row=Record<string,unknown>;
export class HousekeepingRepository{private client=getDatabaseClient();
async snapshot():Promise<HousekeepingSnapshot>{const today=new Date().toISOString().slice(0,10);const[tasks,inspections,inventory,stock,maintenance,interventions,photos,properties,reservations]=await Promise.all([
this.client.from("housekeeping_tasks").select("*").order("scheduled_for"),this.client.from("housekeeping_inspections").select("*").order("created_at",{ascending:false}).limit(200),this.client.from("inventory_items").select("*").order("room").limit(1000),this.client.from("stock_items").select("*").order("name").limit(1000),this.client.from("maintenance_incidents").select("*").order("created_at",{ascending:false}).limit(500),this.client.from("maintenance_interventions").select("*").order("planned_for").limit(500),this.client.from("operational_photos").select("*").order("taken_at",{ascending:false}).limit(500),this.client.from("properties").select("id,slug,name"),this.client.from("reservations").select("id,reference,arrival,departure,status")]);
const failed=[tasks,inspections,inventory,stock,maintenance,interventions,photos,properties,reservations].find(r=>r.error);if(failed?.error)throw new Error(`HOUSEKEEPING_READ_FAILED:${failed.error.code}`);
const props=(properties.data??[])as Row[];const prop=new Map(props.map(r=>[String(r.id),r]));const reservationsRows=(reservations.data??[])as Row[];const res=new Map(reservationsRows.map(r=>[String(r.id),r]));const incidentRows=(maintenance.data??[])as Row[];const incident=new Map(incidentRows.map(r=>[String(r.id),r]));const taskRows=(tasks.data??[])as Row[];const stockRows=(stock.data??[])as Row[];
const completedDurations=taskRows.filter(r=>r.started_at&&r.completed_at).map(r=>(Date.parse(String(r.completed_at))-Date.parse(String(r.started_at)))/60000);
const recommendations=stockRows.filter(r=>Number(r.quantity)<=Number(r.alert_threshold)).map(r=>`Commander ${Math.max(0,Number(r.target_quantity)-Number(r.quantity))} ${r.unit} de ${r.name} pour ${prop.get(String(r.property_id))?.name??"le stock central"}`);
return{generatedAt:new Date().toISOString(),metrics:{arrivals:reservationsRows.filter(r=>r.arrival===today&&!["cancelled","declined"].includes(String(r.status))).length,departures:reservationsRows.filter(r=>r.departure===today&&!["cancelled","declined"].includes(String(r.status))).length,ready:taskRows.filter(r=>r.operational_status==="ready").length,preparing:taskRows.filter(r=>r.operational_status==="to_prepare").length,cleaning:taskRows.filter(r=>r.operational_status==="cleaning").length,blocked:taskRows.filter(r=>r.operational_status==="blocked").length,urgent:incidentRows.filter(r=>r.priority==="urgent"&&!["resolved","closed"].includes(String(r.status))).length,lowStock:recommendations.length,averageCleaningMinutes:completedDurations.length?Math.round(completedDurations.reduce((a,b)=>a+b,0)/completedDurations.length):0,averageInspectionMinutes:0,maintenanceCostCents:incidentRows.reduce((s,r)=>s+Number(r.cost_cents),0)},
properties:props.map(r=>({id:String(r.id),slug:String(r.slug),name:String(r.name)})),tasks:taskRows.map(r=>({id:String(r.id),propertyId:String(r.property_id),propertyName:String(prop.get(String(r.property_id))?.name??"Maison"),reservationReference:String(res.get(String(r.reservation_id))?.reference??"—"),scheduledFor:String(r.scheduled_for),assignee:String(r.assignee??""),status:String(r.status),operationalStatus:String(r.operational_status),checklist:Array.isArray(r.checklist)?r.checklist as HousekeepingSnapshot["tasks"][number]["checklist"]:[],notes:String(r.notes??""),startedAt:r.started_at?String(r.started_at):null,completedAt:r.completed_at?String(r.completed_at):null,offlineRevision:Number(r.offline_revision)})),
inspections:((inspections.data??[])as Row[]).map(r=>{const task=taskRows.find(t=>String(t.id)===String(r.task_id));return{id:String(r.id),taskId:String(r.task_id),propertyName:String(prop.get(String(task?.property_id))?.name??"Maison"),inspector:String(r.inspector),rating:r.rating?Number(r.rating):null,remarks:String(r.remarks??""),status:String(r.status),inspectedAt:r.inspected_at?String(r.inspected_at):null,createdAt:String(r.created_at)}}),
inventory:((inventory.data??[])as Row[]).map(r=>({id:String(r.id),propertyId:String(r.property_id),propertyName:String(prop.get(String(r.property_id))?.name??"Maison"),room:String(r.room),category:String(r.category),name:String(r.name),quantity:Number(r.quantity),valueCents:Number(r.unit_value_cents),condition:String(r.condition),purchasedOn:r.purchased_on?String(r.purchased_on):null,warrantyUntil:r.warranty_until?String(r.warranty_until):null})),
stock:stockRows.map(r=>({id:String(r.id),propertyId:r.property_id?String(r.property_id):null,propertyName:String(prop.get(String(r.property_id))?.name??"Stock central"),category:String(r.category),name:String(r.name),quantity:Number(r.quantity),threshold:Number(r.alert_threshold),target:Number(r.target_quantity),unit:String(r.unit),low:Number(r.quantity)<=Number(r.alert_threshold),lastRestockedAt:r.last_restocked_at?String(r.last_restocked_at):null})),
maintenance:incidentRows.map(r=>({id:String(r.id),propertyId:String(r.property_id),propertyName:String(prop.get(String(r.property_id))?.name??"Maison"),title:String(r.title),description:String(r.description??""),priority:String(r.priority),status:String(r.status),assignee:String(r.assignee??""),costCents:Number(r.cost_cents),dueAt:r.due_at?String(r.due_at):null,createdAt:String(r.created_at)})),
interventions:((interventions.data??[])as Row[]).map(r=>{const inc=incident.get(String(r.incident_id));return{id:String(r.id),incidentId:String(r.incident_id),incidentTitle:String(inc?.title??"Intervention"),propertyName:String(prop.get(String(inc?.property_id))?.name??"Maison"),assignee:String(r.assignee??""),provider:String(r.provider??""),status:String(r.status),plannedFor:r.planned_for?String(r.planned_for):null,completedAt:r.completed_at?String(r.completed_at):null,costCents:Number(r.cost_cents),notes:String(r.notes??"")}}),
photos:((photos.data??[])as Row[]).map(r=>({id:String(r.id),propertyName:String(prop.get(String(r.property_id))?.name??"Maison"),kind:String(r.kind),storagePath:String(r.storage_path),caption:String(r.caption??""),takenAt:String(r.taken_at)})),recommendations};}
async execute(input:HousekeepingAction){if(input.action==="update_task"){const done=input.operationalStatus==="ready";const{data,error}=await this.client.from("housekeeping_tasks").update({operational_status:input.operationalStatus,status:done?"completed":"in_progress",checklist:input.checklist,started_at:input.operationalStatus==="cleaning"?new Date().toISOString():undefined,completed_at:done?new Date().toISOString():null,offline_revision:input.offlineRevision+1}).eq("id",input.taskId).eq("offline_revision",input.offlineRevision).select("id,offline_revision").single();if(error)throw new Error(error.code==="PGRST116"?"OFFLINE_CONFLICT":`TASK_UPDATE_FAILED:${error.code}`);return data;}
if(input.action==="inspect"){const{data,error}=await this.client.from("housekeeping_inspections").insert({task_id:input.taskId,inspector:input.inspector,rating:input.rating??null,remarks:input.remarks??null,status:input.status,inspected_at:new Date().toISOString()}).select("id").single();if(error)throw new Error(`INSPECTION_FAILED:${error.code}`);await this.client.from("housekeeping_tasks").update({operational_status:input.status==="approved"?"ready":"cleaning"}).eq("id",input.taskId);return data;}
if(input.action==="adjust_stock"){const{data,error}=await this.client.from("stock_items").update({quantity:input.quantity,last_restocked_at:new Date().toISOString()}).eq("id",input.stockId).select("id").single();if(error)throw new Error(`STOCK_UPDATE_FAILED:${error.code}`);return data;}
if(input.action==="create_inventory"){const{data,error}=await this.client.from("inventory_items").insert({property_id:input.propertyId,room:input.room,category:input.category,name:input.name,quantity:input.quantity,unit_value_cents:input.unitValueCents,condition:input.condition}).select("id").single();if(error)throw new Error(`INVENTORY_FAILED:${error.code}`);return data;}
if(input.action==="plan_intervention"){const{data,error}=await this.client.from("maintenance_interventions").insert({incident_id:input.incidentId,assignee:input.assignee??null,provider:input.provider??null,planned_for:input.plannedFor,notes:input.notes??null}).select("id").single();if(error)throw new Error(`INTERVENTION_FAILED:${error.code}`);return data;}
const{data,error}=await this.client.from("maintenance_interventions").update({status:input.status,completed_at:input.status==="completed"?new Date().toISOString():null}).eq("id",input.interventionId).select("id").single();if(error)throw new Error(`INTERVENTION_UPDATE_FAILED:${error.code}`);return data;}
}
