import type { StayAccessPayload } from "@/platform/traveler/contracts";
import { commitments, rentalClauses } from "./clauses";

const escape = (value: string | number) => String(value).replace(/[&<>"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "\"": "&quot;", "'": "&#39;" })[character]!);
export function createContractHtml(stay: StayAccessPayload) {
  const detail = stay.contractDetails;
  const issuedOn = detail?.issuedOn ?? new Date().toISOString().slice(0, 10);
  return `<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Contrat ${escape(stay.reference)}</title>
  <style>@page{size:A4;margin:16mm}*{box-sizing:border-box}body{margin:0;color:#102b35;background:#eee7dc;font:11pt Arial,sans-serif}main{max-width:210mm;margin:auto;background:#fbfaf7}.page{min-height:265mm;padding:18mm;page-break-after:always}.cover{color:white;background:linear-gradient(135deg,#0a2733,#34535b);display:flex;flex-direction:column;justify-content:flex-end}h1,h2{font-family:Georgia,serif;font-weight:400}h1{font-size:38pt;line-height:1}h2{font-size:24pt}.eyebrow{color:#b59463;text-transform:uppercase;letter-spacing:2px;font-size:8pt}.grid{display:grid;grid-template-columns:1fr 1fr;gap:8mm}.card{padding:6mm;border:1px solid #d9d1c5}.line{display:flex;justify-content:space-between;gap:8mm;padding:3mm 0;border-bottom:1px solid #ddd}.clause{break-inside:avoid;margin-bottom:6mm}.signature{height:35mm;border-bottom:1px solid #999}.warning{padding:4mm;background:#f3e6d3}@media(max-width:700px){.grid{grid-template-columns:1fr}.page{padding:8mm}}@media print{body{background:white}main{max-width:none}}</style></head>
  <body><main><section class="page cover"><p class="eyebrow">Beaux Rivages · Contrat de location saisonnière</p><h1>${escape(stay.propertyName)}</h1><p>${escape(stay.arrival)} → ${escape(stay.departure)} · ${escape(stay.guests)} voyageurs</p><p>Réservation ${escape(stay.reference)} · Émis le ${escape(issuedOn)}</p></section>
  <section class="page"><p class="eyebrow">Les parties</p><h2>Votre réservation</h2>${detail ? `<div class="grid"><div class="card"><h3>Voyageur</h3><p>${escape(detail.travelerFirstName)} ${escape(detail.travelerLastName)}<br>${escape(detail.address)}<br>${escape(detail.phone)}<br>${escape(detail.email)}</p></div><div class="card"><h3>Séjour</h3><p>${escape(stay.propertyName)}<br>${escape(stay.arrival)} au ${escape(stay.departure)}<br>${detail.adults} adultes · ${detail.children} enfants · ${detail.babies} bébés · ${detail.pets} animaux</p></div></div><h2>Décompte</h2><div class="line"><span>Nuits</span><strong>${detail.nightsPrice} €</strong></div><div class="line"><span>Ménage</span><strong>${detail.cleaningFee} €</strong></div><div class="line"><span>Taxe de séjour</span><strong>${detail.touristTax} €</strong></div><div class="line"><span>Options</span><strong>${detail.optionsTotal} €</strong></div><div class="line"><span>Total</span><strong>${detail.total} €</strong></div>` : `<p class="warning">Les coordonnées complètes et le décompte doivent être renseignés avant signature.</p>`}</section>
  <section class="page"><p class="eyebrow">Conditions</p><h2>Conditions de location</h2>${rentalClauses.map((clause) => `<article class="clause"><h3>${escape(clause.title)}</h3><p>${escape(clause.text)}</p></article>`).join("")}</section>
  <section class="page"><p class="eyebrow">Notre promesse</p><h2>Les engagements Beaux Rivages</h2><ul>${commitments.map((item) => `<li>${escape(item)}</li>`).join("")}</ul><h2>Vos hôtes</h2><p>Stéphanie Coulot<br>+33 6 17 26 00 94<br>coulotstephanie@gmail.com</p><h3>Urgences</h3><p>Urgence européenne : 112 · SAMU : 15 · Pompiers : 18. Les médecins et pharmacies de garde doivent être vérifiés localement au moment du besoin.</p></section>
  <section class="page"><p class="eyebrow">Annexes et signatures</p><h2>Documents annexés</h2><ul><li>État descriptif et inventaire</li><li>État des lieux</li><li>Plan du logement</li><li>Consignes d’arrivée et de départ</li><li>Règlement intérieur</li></ul><div class="grid"><div><h3>Le locataire</h3><div class="signature"></div><p>Nom, date et signature</p></div><div><h3>Le propriétaire</h3><div class="signature"></div><p>Stéphanie Coulot, date et signature</p></div></div><p class="warning">Architecture préparée pour une future signature Yousign, DocuSign ou prestataire équivalent. Ce modèle doit être validé juridiquement et complété avec les identifiants réglementaires avant usage.</p></section></main></body></html>`;
}
