import type { StayAccessPayload } from "@/platform/traveler/contracts";
import { commitments, rentalClauses } from "./clauses";

const escape = (value: string | number) =>
  String(value).replace(
    /[&<>"']/g,
    (character) =>
      ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[character]!,
  );
export function createContractHtml(stay: StayAccessPayload) {
  const detail = stay.contractDetails;
  const issuedOn = detail?.issuedOn ?? new Date().toISOString().slice(0, 10);
  const includedBasket = stay.options.find((item) => item.startsWith("Panier inclus ·"));
  const additionalBasket = stay.options.find(
    (item) =>
      !item.startsWith("Panier inclus ·") &&
      (item.includes("Panier Apéritif") || item.includes("Panier Douceur")),
  );
  const basketIncludedLabel =
    includedBasket?.replace("Panier inclus · ", "") ?? additionalBasket ?? "Aucun";
  const basketAdditionalLabel =
    includedBasket && additionalBasket ? `${additionalBasket} · 45 €` : "Aucun";
  return `<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Contrat ${escape(stay.reference)}</title>
  <style>@page{size:A4;margin:16mm}*{box-sizing:border-box}body{margin:0;color:#16354A;background:#F7F3EA;font:11pt Arial,sans-serif}main{max-width:210mm;margin:auto;background:#fff}.page{min-height:265mm;padding:18mm;page-break-after:always}.cover{color:white;background:#16354A;display:flex;flex-direction:column;justify-content:flex-end}.contract-logo{width:75mm;margin-bottom:auto}h1,h2{font-family:Georgia,serif;font-weight:400}h1{font-size:38pt;line-height:1}h2{font-size:24pt}.eyebrow{color:#B99A63;text-transform:uppercase;letter-spacing:2px;font-size:8pt}.grid{display:grid;grid-template-columns:1fr 1fr;gap:8mm}.card{padding:6mm;border:1px solid #D8C3A5}.line{display:flex;justify-content:space-between;gap:8mm;padding:3mm 0;border-bottom:1px solid #ddd}.clause{break-inside:avoid;margin-bottom:6mm}.signature{height:35mm;border-bottom:1px solid #999}.warning{padding:4mm;background:#F7F3EA}@media(max-width:700px){.grid{grid-template-columns:1fr}.page{padding:8mm}}@media print{body{background:white}main{max-width:none}}</style></head>
  <body><main><section class="page cover"><svg class="contract-logo" viewBox="0 0 760 150" aria-label="Beaux Rivages"><g transform="translate(28 18)" fill="none" stroke="#fff" stroke-linecap="round" stroke-linejoin="round"><path d="M26 19V81M26 20H48C62 20 69 27 69 37C69 47 61 53 48 53H26M48 53C64 53 74 62 76 79" stroke-width="5.2"/><path d="M52 20V81M52 20H69C82 20 89 27 89 37C89 47 81 53 69 53H52M69 53L91 81" stroke-width="3.2"/><path d="M14 69C31 61 43 61 58 69C73 77 85 77 100 68" stroke-width="2.2"/></g><text x="162" y="70" fill="#fff" font-family="Optima,Arial,sans-serif" font-size="31" letter-spacing="6">BEAUX RIVAGES</text></svg><p class="eyebrow">Contrat de location saisonnière</p><h1>${escape(stay.propertyName)}</h1><p>${escape(stay.arrival)} → ${escape(stay.departure)} · ${escape(stay.guests)} voyageurs</p><p>Réservation ${escape(stay.reference)} · Émis le ${escape(issuedOn)}</p></section>
  <section class="page"><p class="eyebrow">Les parties</p><h2>Votre réservation</h2>${detail ? `<div class="grid"><div class="card"><h3>Voyageur</h3><p>${escape(detail.travelerFirstName)} ${escape(detail.travelerLastName)}<br>${escape(detail.address)}<br>${escape(detail.phone)}<br>${escape(detail.email)}</p></div><div class="card"><h3>Séjour</h3><p>${escape(stay.propertyName)}<br>${escape(stay.arrival)} au ${escape(stay.departure)}<br>${detail.adults} adultes · ${detail.children} enfants · ${detail.babies} bébés · ${detail.pets} animaux</p></div></div><h2>Prestations choisies</h2><p>${escape(stay.options.join(", ") || "Aucune option")}</p><p><strong>Expériences</strong><br>${escape(stay.experiences?.join(", ") || "Aucune")}</p>${stay.specialRequests && Object.values(stay.specialRequests).some(Boolean) ? `<p><strong>Demandes particulières</strong><br>${escape([stay.specialRequests.occasion, stay.specialRequests.message, stay.specialRequests.allergies, stay.specialRequests.lateArrival].filter(Boolean).join(" · "))}</p>` : ""}<p><strong>Accueil gourmand</strong><br>Panier inclus : ${escape(basketIncludedLabel)}<br>Panier supplémentaire : ${escape(basketAdditionalLabel)}</p><h2>Décompte</h2><div class="line"><span>Nuits</span><strong>${detail.nightsPrice} €</strong></div><div class="line"><span>Ménage</span><strong>${detail.cleaningFee} €</strong></div><div class="line"><span>Taxe de séjour</span><strong>${detail.touristTax} €</strong></div><div class="line"><span>Options et expériences</span><strong>${detail.optionsTotal} €</strong></div><div class="line"><span>Montant total du séjour</span><strong>${detail.total} €</strong></div><div class="line"><span>Acompte exigible</span><strong>${detail.depositDue ?? stay.depositPaid} €</strong></div><div class="line"><span>Solde restant</span><strong>${detail.balanceDue ?? stay.balanceRemaining} €</strong></div><div class="line"><span>Date limite du solde</span><strong>${escape(detail.balanceDueDate ?? "Paiement intégral immédiat")}</strong></div>` : `<p class="warning">Les coordonnées complètes et le décompte doivent être renseignés avant signature.</p>`}</section>
  <section class="page"><p class="eyebrow">Conditions</p><h2>Conditions de location</h2>${rentalClauses.map((clause) => `<article class="clause"><h3>${escape(clause.title)}</h3><p>${escape(clause.text)}</p></article>`).join("")}<h3>Annulation</h3><p>Annulation gratuite pendant 24 heures après la réservation, hors réservation effectuée moins de 14 jours avant l’arrivée. Après ce délai, l’acompte de 30 % reste acquis. À moins de 14 jours de l’arrivée, le séjour est intégralement dû, sauf obligation légale contraire.</p><p><strong>Le locataire reconnaît avoir pris connaissance et accepté les Conditions Générales de Vente de Beaux Rivages${detail?.termsVersion ? `, version ${escape(detail.termsVersion)}` : ""}, ainsi que la Politique d’annulation${detail?.cancellationVersion ? `, version ${escape(detail.cancellationVersion)}` : ""}.</strong></p><p><a href="https://www.beaux-rivages.com/conditions-generales-de-vente">Conditions Générales de Vente</a><br><a href="https://www.beaux-rivages.com/politique-annulation">Politique d’annulation</a></p></section>
  <section class="page"><p class="eyebrow">Notre promesse</p><h2>Les engagements Beaux Rivages</h2><ul>${commitments.map((item) => `<li>${escape(item)}</li>`).join("")}</ul><h2>Vos hôtes</h2><p>Stéphanie Coulot<br>+33 6 17 26 00 94<br>coulotstephanie@gmail.com</p><h3>Urgences</h3><p>Urgence européenne : 112 · SAMU : 15 · Pompiers : 18. Les médecins et pharmacies de garde doivent être vérifiés localement au moment du besoin.</p></section>
  <section class="page"><p class="eyebrow">Annexes et signatures</p><h2>Documents annexés</h2><ul><li>État descriptif et inventaire</li><li>État des lieux</li><li>Plan du logement</li><li>Consignes d’arrivée et de départ</li><li>Règlement intérieur</li></ul><div class="grid"><div><h3>Le locataire</h3><div class="signature"></div><p>Nom, date et signature</p></div><div><h3>Le propriétaire</h3><div class="signature"></div><p>Stéphanie Coulot, date et signature</p></div></div><p class="warning">Architecture préparée pour une future signature Yousign, DocuSign ou prestataire équivalent. Ce modèle doit être validé juridiquement et complété avec les identifiants réglementaires avant usage.</p></section></main></body></html>`;
}
