export type TravelerDocument = { id: string; title: string; url: string; availableFrom: string; sensitive: boolean };
export type ArrivalInformation = { propertySlug: string; availableFrom: string; parking: string; checkIn: string; contact: string };
export type TravelerPortal = {
  travelerId: string;
  reservationIds: string[];
  selectedExperienceSlugs: string[];
  guideSlugs: string[];
  recommendationSlugs: string[];
  documents: TravelerDocument[];
  arrival: ArrivalInformation | null;
};
export type StayAccessPayload = {
  reservationId: string;
  reference: string;
  travelerName: string;
  propertySlug: string;
  propertyName: string;
  arrival: string;
  departure: string;
  guests: number;
  depositPaid: number;
  balanceRemaining: number;
  currency: "EUR";
  options: string[];
  guideSlugs: string[];
  documents: { id: string; title: string; kind: "contract" | "conditions" | "invoice" }[];
  arrivalDetails?: { availableFrom: string; accessCode?: string; parking?: string };
  contractDetails?: {
    travelerFirstName: string;
    travelerLastName: string;
    address: string;
    phone: string;
    email: string;
    adults: number;
    children: number;
    babies: number;
    pets: number;
    nightsPrice: number;
    cleaningFee: number;
    touristTax: number;
    optionsTotal: number;
    total: number;
    issuedOn: string;
    wifiQrValue?: string;
  };
  expiresAt: string;
};
