"use client";
import { FormEvent,useEffect,useMemo,useState } from "react";
type Catalog={categories:{id:string;code:string;label:string;description:string}[];experiences:{id:string;categoryId:string;code:string;title:string;description:string;inclusions:string[];priceCents:number;pricingUnit:string;requiresConfirmation:boolean}[]};
const sections=[["home","Accueil"],["experiences","Expériences"],["services","Services"],["gourmet","Paniers gourmands"],["wellness","Bien-être"],["family","Famille"],["pets","Animaux"],["mobility","Mobilité"],["special","Demandes spéciales"],["cart","Mon panier"],["history","Historique"]];
const money=(c:number)=>new Intl.NumberFormat("fr-FR",{style:"currency",currency:"EUR"}).format(c/100);
export function ConciergePremium() {
  const [catalog,setCatalog]=useState<Catalog|null>(null);const [active,setActive]=useState("home");const [cart,setCart]=useState<Record<string,number>>({});const [message,setMessage]=useState("");const [locale,setLocale]=useState<"fr"|"en"|"de">("fr");
  useEffect(()=>{fetch(`/api/concierge?locale=${locale}`).then((r)=>r.json()).then(setCatalog).catch(()=>setMessage("Le catalogue est momentanément indisponible."));},[locale]);
  const items=useMemo(()=>catalog?.experiences.filter((item)=>cart[item.id])??[],[catalog,cart]);const total=items.reduce((sum,item)=>sum+item.priceCents*cart[item.id],0);
  const recommendations=useMemo(()=>catalog?.experiences.filter((item)=>["romance","baby-kit","pet-welcome","basket-aperitif"].includes(item.code))??[],[catalog]);
  const add=(id:string)=>setCart((current)=>({...current,[id]:(current[id]??0)+1}));
  if(!catalog)return <section className="shell concierge-premium-loading"><p>{message||"Préparation de vos expériences…"}</p></section>;
  const visible=active==="experiences"?catalog.experiences:catalog.experiences.filter((item)=>catalog.categories.find((category)=>category.id===item.categoryId)?.code===active);
  return <section className="concierge-premium shell">
    <div className="concierge-premium__toolbar"><nav aria-label="Personnalisez votre séjour">{sections.map(([id,label])=><button type="button" key={id} aria-current={active===id?"page":undefined} onClick={()=>setActive(id)}>{label}{id==="cart"&&items.length?` (${items.length})`:""}</button>)}</nav><select aria-label="Langue" value={locale} onChange={(event)=>setLocale(event.target.value as typeof locale)}><option value="fr">FR</option><option value="en">EN</option><option value="de">DE</option></select></div>
    {active==="home"&&<><div className="concierge-welcome"><p className="eyebrow">Quelques attentions, choisies pour vous</p><h2>Composez un séjour qui vous ressemble.</h2><p>Chaque expérience est préparée avec soin par Stéphanie, Bruno et leurs partenaires locaux.</p></div><div className="concierge-recommendations">{recommendations.map((item)=><ExperienceCard key={item.id} item={item} quantity={cart[item.id]??0} add={add}/>)}</div><RecommendationNote/></>}
    {!["home","special","cart","history"].includes(active)&&<div className="concierge-catalog">{visible.map((item)=><ExperienceCard key={item.id} item={item} quantity={cart[item.id]??0} add={add}/>)}</div>}
    {active==="special"&&<SpecialRequest message={message} setMessage={setMessage}/>}
    {active==="cart"&&<Cart catalog={catalog} cart={cart} setCart={setCart} total={total} message={message} setMessage={setMessage}/>}
    {active==="history"&&<div className="concierge-welcome"><p className="eyebrow">Historique</p><h2>Retrouvez vos demandes confirmées.</h2><p>Votre historique détaillé est associé à votre réservation et apparaît dans votre Carnet Beaux Rivages. Pour préserver vos données, il n’est jamais stocké dans ce navigateur.</p></div>}
  </section>;
}
function ExperienceCard({item,quantity,add}:{item:Catalog["experiences"][number];quantity:number;add:(id:string)=>void}) {return <article className={`concierge-experience concierge-experience--${item.code}`}><span>{item.requiresConfirmation?"Selon disponibilité":"Disponible"}</span><h3>{item.title}</h3><p>{item.description}</p>{Array.isArray(item.inclusions)&&item.inclusions.length>0&&<ul>{item.inclusions.map((line)=><li key={line}>{line}</li>)}</ul>}<div><strong>{item.priceCents?money(item.priceCents):"Sur demande"}</strong><button type="button" onClick={()=>add(item.id)}>{quantity?`Ajouté · ${quantity}`:"Ajouter à mon séjour"}</button></div></article>;}
function RecommendationNote(){return <aside className="concierge-ai"><p className="eyebrow">Suggestion personnalisée</p><h3>Une attention juste, jamais superflue.</h3><p>En couple, découvrez l’Escapade Romance. Avec un bébé, privilégiez l’équipement famille. Avec votre chien, l’accueil animal rassemble gamelles, balades et plages autorisées. Pour un séjour plus long, un panier gourmand accompagne les premiers instants.</p></aside>;}
function IdentityFields(){return <><label>Référence de réservation<input name="reservationReference" required placeholder="BR-2026-…" /></label><label>E-mail de la réservation<input name="email" type="email" required /></label></>;}
function Cart({catalog,cart,setCart,total,message,setMessage}:{catalog:Catalog;cart:Record<string,number>;setCart:(v:Record<string,number>)=>void;total:number;message:string;setMessage:(v:string)=>void}) {const chosen=catalog.experiences.filter((item)=>cart[item.id]);const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const f=new FormData(event.currentTarget);const response=await fetch("/api/concierge",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"order",reservationReference:f.get("reservationReference"),email:f.get("email"),locale:"fr",promotionCode:f.get("promotionCode")||undefined,message:f.get("message")||undefined,items:chosen.map((item)=>({experienceId:item.id,quantity:cart[item.id]}))})});const body=await response.json();setMessage(response.ok?"Votre demande est transmise. Stéphanie vous confirmera chaque expérience avant le paiement.":body.error??"Demande impossible.");if(response.ok)setCart({});};return <div className="concierge-cart"><h2>Les expériences de votre séjour</h2>{chosen.length?<>{chosen.map((item)=><div key={item.id}><div><strong>{item.title}</strong><span>{money(item.priceCents)} × {cart[item.id]}</span></div><input aria-label={`Quantité ${item.title}`} type="number" min="1" max="30" value={cart[item.id]} onChange={(event)=>setCart({...cart,[item.id]:Number(event.target.value)})}/><button type="button" onClick={()=>{const next={...cart};delete next[item.id];setCart(next);}}>Retirer</button></div>)}<strong className="concierge-cart__total">Total estimé · {money(total)}</strong><form onSubmit={submit}><IdentityFields/><label>Code privilège<input name="promotionCode"/></label><label>Un mot pour nous<textarea name="message" rows={3}/></label><button>Envoyer ma demande</button></form></>:<p>Votre sélection est encore vide.</p>}<p role="status">{message}</p></div>;}
function SpecialRequest({message,setMessage}:{message:string;setMessage:(v:string)=>void}) {const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const f=new FormData(event.currentTarget);const response=await fetch("/api/concierge",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"special_request",reservationReference:f.get("reservationReference"),email:f.get("email"),occasion:f.get("occasion"),details:f.get("details"),allergies:f.get("allergies")||undefined,dietaryRequirements:f.get("diet")||undefined})});const body=await response.json();setMessage(response.ok?"Votre demande a bien été transmise à Stéphanie et Bruno.":body.error??"Demande impossible.");};return <form className="concierge-special" onSubmit={submit}><p className="eyebrow">Une attention imaginée pour vous</p><h2>Parlez-nous de votre projet.</h2><IdentityFields/><label>Occasion<select name="occasion"><option value="birthday">Anniversaire</option><option value="wedding">Mariage</option><option value="proposal">Demande en mariage</option><option value="baby">Bébé</option><option value="surprise">Surprise</option><option value="allergies">Allergies</option><option value="diet">Régime alimentaire</option><option value="other">Autre</option></select></label><label>Votre demande<textarea name="details" minLength={5} rows={5} required/></label><label>Allergies éventuelles<input name="allergies"/></label><label>Régime alimentaire<input name="diet"/></label><button>Confier ma demande</button><p role="status">{message}</p></form>;}
