import type { GuestBookEntry } from "./types";

const base = {
  house: "chai-des-tortues",
  status: "published",
  createdAt: "2026-07-31T00:00:00Z",
  updatedAt: "2026-07-31T00:00:00Z",
} as const;

export const initialGuestBookEntries: GuestBookEntry[] = [
  {
    ...base,
    id: "a0000000-0000-4000-8000-000000000001",
    date: "2026-03",
    language: "fr",
    author: "Anne & Lydie",
    featured: true,
    tags: ["Accueil", "Disponibilité", "Literie", "Confort", "Retour"],
    image: null,
    text: "Quel beau séjour nous avons passé dans votre Chai. Merci pour votre disponibilité et votre réactivité. Les espaces sont bien pensés et le lieu est très agréable à vivre. Une literie fantastique ! Encore un grand merci Stéphanie et Bruno. Nous reviendrons avec grand plaisir.",
  },
  {
    ...base,
    id: "a0000000-0000-4000-8000-000000000002",
    date: "2026-03",
    language: "fr",
    author: "Cédric, Mélissa et leurs enfants",
    featured: true,
    tags: ["Famille", "Confort", "Cuisine", "Literie", "Retour"],
    image: null,
    text: "Merci beaucoup Stéphanie et Bruno. Nous avons passé un très agréable séjour. Votre région a été une découverte incroyable. Le logement est parfaitement aménagé, très bien pensé et la literie est TOP. Merci pour tout.",
  },
  {
    ...base,
    id: "a0000000-0000-4000-8000-000000000003",
    date: "2026-03",
    language: "fr",
    author: "Famille",
    featured: true,
    tags: ["Équipements", "Propreté", "Accueil", "Retour"],
    image: null,
    text: "Tout est parfait : l'équipement, le confort, la propreté de la maison. Stéphanie et Bruno sont des hôtes attentifs, disponibles mais discrets. Tout est réuni pour un superbe séjour. Nous avons envie de revenir.",
  },
  {
    ...base,
    id: "a0000000-0000-4000-8000-000000000004",
    date: "2026-03-20",
    language: "fr",
    author: "Élise & Guillaume",
    featured: false,
    tags: ["Accueil", "Emplacement", "Confort"],
    image: null,
    text: "Merci beaucoup à Stéphanie et Bruno pour leur disponibilité. Le gîte est très bien équipé et très agréable à vivre. De plus, il est très bien situé.",
  },
  {
    ...base,
    id: "a0000000-0000-4000-8000-000000000005",
    date: "2026-04-24",
    language: "fr",
    author: "Valentina (11 ans)",
    featured: true,
    tags: ["Famille", "Île de Ré", "Vacances"],
    image: null,
    text: "Merci pour tout Stéphanie et Bruno. La maison est incroyable ! Un très beau souvenir à l'Île de Ré. C'est une très belle île où il y a des coquillages et des vélos. Bonnes vacances !",
  },
  {
    ...base,
    id: "a0000000-0000-4000-8000-000000000006",
    date: "2026-04",
    language: "fr",
    author: "Famille",
    featured: false,
    tags: ["Séjour", "Retour"],
    image: null,
    text: "Merci beaucoup pour cette magnifique maison. Nous avons passé un incroyable séjour. À très vite.",
  },
  {
    ...base,
    id: "a0000000-0000-4000-8000-000000000007",
    date: "2026-04",
    language: "fr",
    author: "Astrid, Benjamin et leurs enfants",
    featured: false,
    tags: ["Famille", "Séjour"],
    image: null,
    text: "Merci beaucoup pour cet agréable séjour dans cette maison.",
  },
  {
    ...base,
    id: "a0000000-0000-4000-8000-000000000008",
    date: "2026-07-29",
    language: "en",
    author: "Bart, Nynke, Aline, Yfke & Eize",
    featured: true,
    tags: ["International", "Welcome", "House", "Island"],
    image: null,
    text: "Thanks for everything! We had a wonderful stay and really enjoyed being here in this lovely house and on this beautiful island. Everything was taken care of and we felt very welcome.",
  },
];
