"use client";
import { FormEvent, useEffect, useState } from "react";
import type { ChannelManagerSnapshot } from "@/platform/channel-manager/contracts";
import type { BackOfficeSnapshot } from "@/platform/admin/contracts";

type Section = "dashboard"|"calendar"|"platforms"|"syncs"|"conflicts"|"logs"|"settings";
const labels: Record<Section,string> = { dashboard:"Dashboard",calendar:"Calendrier",platforms:"Plateformes",syncs:"Synchronisations",conflicts:"Conflits",logs:"Logs",settings:"Paramètres" };
const dt = (v:string|null) => v ? new Intl.DateTimeFormat("fr-FR",{ dateStyle:"short",timeStyle:"short" }).format(new Date(v)) : "Jamais";

export function ChannelManagerAdmin({ token, properties, notify }: { token:string; properties:BackOfficeSnapshot["properties"]; notify:(value:string)=>void }) {
  const [data,setData] = useState<ChannelManagerSnapshot|null>(null); const [section,setSection] = useState<Section>("dashboard"); const [busy,setBusy] = useState(false);
  const call = async (payload?:Record<string,unknown>) => { setBusy(true); try { const response = await fetch("/api/admin/channel-manager",{ method:payload ? "POST":"GET",headers:{ Authorization:`Bearer ${token}`,"Content-Type":"application/json" },body:payload ? JSON.stringify(payload):undefined }); const body = await response.json(); if (!response.ok) return notify(body.error ?? "Channel Manager indisponible."); if (payload) notify("Action Channel Manager enregistrée et journalisée."); const refresh = payload ? await fetch("/api/admin/channel-manager",{ headers:{ Authorization:`Bearer ${token}` } }) : response; setData(payload ? await refresh.json():body); } finally { setBusy(false); } };
  useEffect(() => { void call(); }, []); // eslint-disable-line react-hooks/exhaustive-deps
  if (!data) return <section className="admin-panel"><p>{busy ? "Chargement du Channel Manager…" : "Aucune donnée disponible."}</p></section>;
  return <section className="admin-panel"><div className="admin-panel__heading"><div><p className="eyebrow">Source de vérité des réservations</p><h2>Channel Manager Premium</h2></div><button type="button" disabled={busy} onClick={() => void call()}>Actualiser</button></div>
    <nav className="revenue-tabs" aria-label="Channel Manager">{(Object.keys(labels) as Section[]).map((item) => <button type="button" key={item} aria-current={section===item ? "page":undefined} onClick={() => setSection(item)}>{labels[item]}</button>)}</nav>
    {section==="dashboard" && <><div className="admin-kpis"><K label="Réservations synchronisées" value={data.metrics.synchronizedReservations}/><K label="Dernière synchro" value={dt(data.metrics.lastSyncAt)}/><K label="En cours" value={data.metrics.running}/><K label="Erreurs" value={data.metrics.errors}/><K label="Alertes" value={data.metrics.alerts}/><K label="Conflits" value={data.metrics.conflicts}/></div><div className="admin-two-columns"><article className="admin-card"><h3>État des plateformes</h3>{data.connections.map((item)=><Line key={item.id} title={item.name} detail={`${item.mode} · ${item.capabilities.join(", ")}`} status={item.status}/>)}</article><article className="admin-card"><h3>Dernières synchronisations</h3>{data.jobs.slice(0,8).map((item)=><Line key={item.id} title={`${item.provider} · ${item.resource}`} detail={dt(item.createdAt)} status={item.status}/>)}</article></div></>}
    {section==="calendar" && <div className="admin-calendar-board">{properties.map((property)=><article key={property.id}><h3>{property.name}</h3>{data.calendar.filter((item)=>item.propertyName===property.name).slice(0,20).map((item)=><div className={`admin-calendar-event channel-${item.source}`} key={item.id}><strong>{item.source}</strong><span>{item.range}</span><small>{item.note}</small></div>)}</article>)}</div>}
    {section==="platforms" && <div className="admin-property-grid">{data.connections.map((connection)=><article key={connection.id}><h3>{connection.name}</h3><Line title="Connexion" detail={connection.mode} status={connection.status}/>{data.mappings.filter((item)=>item.connectionId===connection.id).map((mapping)=><Mapping key={mapping.id} mapping={mapping} busy={busy} submit={call}/>)}</article>)}</div>}
    {section==="syncs" && <><div className="admin-actions">{properties.map((property)=><button type="button" disabled={busy} key={property.id} onClick={() => { const connection=data.connections[0]; if(connection) void call({ action:"sync",connectionId:connection.id,propertySlug:property.slug }); }}>Synchroniser {property.name}</button>)}</div><div className="admin-list">{data.jobs.map((item)=><div className="admin-health-row" key={item.id}><div><strong>{item.provider} · {item.direction} {item.resource}</strong><span>{dt(item.startedAt)} · tentative {item.attempt}{item.errorMessage ? ` · ${item.errorMessage}`:""}</span></div><div><span className="admin-status">{item.status}</span>{item.status==="failed" && <button type="button" onClick={() => void call({ action:"retry_job",jobId:item.id })}>Rejouer</button>}</div></div>)}</div></>}
    {section==="conflicts" && <div className="admin-list">{data.conflicts.map((item)=><article className="admin-reservation-row" key={item.id}><div><strong>{item.propertyName} · {item.type}</strong><span>{item.provider} · {item.range} · {item.proposedResolution}</span></div><span className="admin-status">{item.severity}</span><button type="button" disabled={busy} onClick={() => void call({ action:"resolve_conflict",conflictId:item.id,status:"resolved",resolution:"Conflit vérifié et résolu depuis le Back Office" })}>Résoudre</button></article>)}{!data.conflicts.length && <p className="admin-empty">Aucun conflit détecté.</p>}</div>}
    {section==="logs" && <div className="admin-table-wrap"><table><thead><tr><th>Date</th><th>Plateforme</th><th>Action</th><th>Entité</th><th>Acteur</th><th>Réversible</th></tr></thead><tbody>{data.logs.map((item)=><tr key={item.id}><td>{dt(item.createdAt)}</td><td>{item.provider||"interne"}</td><td>{item.action}</td><td>{item.entityType} · {item.entityId}</td><td>{item.actor}</td><td>{item.reversible ? "Oui":"Non"}</td></tr>)}</tbody></table></div>}
    {section==="settings" && <div className="admin-callout"><h3>Connecteurs partenaires</h3><p>Les calendriers iCal synchronisent immédiatement les disponibilités. Les prix, voyageurs, paiements et commentaires nécessitent les accès API officiels de chaque plateforme. Les connecteurs sont isolés du cœur afin d’ajouter Expedia, Holidu, HomeToGo ou Google Vacation Rentals sans modifier le moteur.</p></div>}
  </section>;
}
function K({label,value}:{label:string;value:string|number}) { return <article><span>{label}</span><strong>{value}</strong></article>; }
function Line({title,detail,status}:{title:string;detail:string;status:string}) { return <div className="admin-health-row"><div><strong>{title}</strong><span>{detail}</span></div><span className="admin-status">{status}</span></div>; }
function Mapping({mapping,busy,submit}:{mapping:ChannelManagerSnapshot["mappings"][number];busy:boolean;submit:(p:Record<string,unknown>)=>Promise<void>}) { const save=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const f=new FormData(event.currentTarget);void submit({ action:"update_mapping",mappingId:mapping.id,externalListingId:f.get("externalListingId"),externalListingName:f.get("externalListingName"),syncPrices:f.get("syncPrices")==="on",syncAvailability:f.get("syncAvailability")==="on",syncReservations:f.get("syncReservations")==="on" });};return <form className="channel-mapping" onSubmit={save}><strong>{mapping.propertyName}</strong><input name="externalListingId" defaultValue={mapping.externalListingId} aria-label={`Identifiant ${mapping.propertyName}`} /><input name="externalListingName" defaultValue={mapping.externalListingName} aria-label={`Nom annonce ${mapping.propertyName}`} /><label><input type="checkbox" name="syncAvailability" defaultChecked={mapping.syncAvailability}/> Disponibilités</label><label><input type="checkbox" name="syncReservations" defaultChecked={mapping.syncReservations}/> Réservations</label><label><input type="checkbox" name="syncPrices" defaultChecked={mapping.syncPrices}/> Prix</label><button disabled={busy}>Enregistrer</button></form>; }
