"use client";
import{useEffect,useState}from"react";import type{HousekeepingSnapshot}from"@/platform/housekeeping/contracts";
type Section="dashboard"|"planning"|"quality"|"inventory"|"maintenance"|"interventions"|"stock"|"consumables"|"photos"|"reports";
const sections:Record<Section,string>={dashboard:"Tableau de bord",planning:"Planning ménage",quality:"Contrôles qualité",inventory:"Inventaire",maintenance:"Maintenance",interventions:"Interventions",stock:"Stocks",consumables:"Consommables",photos:"Photos",reports:"Rapports"};
const dt=(v:string|null)=>v?new Intl.DateTimeFormat("fr-FR",{dateStyle:"short",timeStyle:"short"}).format(new Date(v)):"—";const money=(c:number)=>new Intl.NumberFormat("fr-FR",{style:"currency",currency:"EUR"}).format(c/100);
export function HousekeepingAdmin({token,notify}:{token:string;notify:(v:string)=>void}){const[data,setData]=useState<HousekeepingSnapshot|null>(null);const[section,setSection]=useState<Section>("dashboard");const[busy,setBusy]=useState(false);
const call=async(payload?:Record<string,unknown>)=>{setBusy(true);try{const response=await fetch("/api/admin/housekeeping",{method:payload?"POST":"GET",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:payload?JSON.stringify(payload):undefined});const body=await response.json();if(!response.ok){if(payload&&!navigator.onLine){const queue=JSON.parse(localStorage.getItem("br-housekeeping-queue")??"[]");localStorage.setItem("br-housekeeping-queue",JSON.stringify([...queue,payload]));return notify("Modification conservée hors ligne. Elle sera synchronisée au retour du réseau.");}return notify(body.error??"Action impossible.");}if(payload)notify("Donnée opérationnelle synchronisée.");const refresh=payload?await fetch("/api/admin/housekeeping",{headers:{Authorization:`Bearer ${token}`}}):response;setData(payload?await refresh.json():body);}finally{setBusy(false);}};
useEffect(()=>{void call();const sync=async()=>{const queue=JSON.parse(localStorage.getItem("br-housekeeping-queue")??"[]")as Record<string,unknown>[];for(const payload of queue)await call(payload);if(queue.length)localStorage.removeItem("br-housekeeping-queue");};window.addEventListener("online",sync);return()=>window.removeEventListener("online",sync);},[]);// eslint-disable-line react-hooks/exhaustive-deps
if(!data)return <section className="admin-panel"><p>{busy?"Chargement du centre opérationnel…":"Données indisponibles."}</p></section>;
return <section className="admin-panel housekeeping-app"><div className="admin-panel__heading"><div><p className="eyebrow">Centre opérationnel</p><h2>Housekeeping & Maintenance</h2></div><span className={`network-state ${typeof navigator!=="undefined"&&navigator.onLine?"online":"offline"}`}>{typeof navigator!=="undefined"&&navigator.onLine?"Synchronisé":"Mode hors ligne"}</span></div><nav className="revenue-tabs" aria-label="Housekeeping">{(Object.keys(sections)as Section[]).map(id=><button key={id} type="button" aria-current={section===id?"page":undefined} onClick={()=>setSection(id)}>{sections[id]}</button>)}</nav>
{section==="dashboard"&&<><div className="admin-kpis"><K l="Arrivées" v={data.metrics.arrivals}/><K l="Départs" v={data.metrics.departures}/><K l="Maisons prêtes" v={data.metrics.ready}/><K l="En préparation" v={data.metrics.preparing}/><K l="En nettoyage" v={data.metrics.cleaning}/><K l="Bloquées" v={data.metrics.blocked}/><K l="Urgences" v={data.metrics.urgent}/><K l="Stocks faibles" v={data.metrics.lowStock}/></div><div className="admin-two-columns"><article className="admin-card"><h3>Prévisions intelligentes</h3>{data.recommendations.map(item=><p key={item}>• {item}</p>)}{!data.recommendations.length&&<p>Les niveaux actuels ne nécessitent aucun achat.</p>}</article><article className="admin-card"><h3>Performance</h3><p>Temps moyen ménage : <strong>{data.metrics.averageCleaningMinutes||"—"} min</strong></p><p>Coûts maintenance : <strong>{money(data.metrics.maintenanceCostCents)}</strong></p><p>Incidents ouverts : <strong>{data.maintenance.filter(i=>!["resolved","closed"].includes(i.status)).length}</strong></p></article></div></>}
{section==="planning"&&<div className="housekeeping-board">{data.tasks.map(task=><TaskCard key={task.id} task={task} busy={busy} submit={call}/>)}</div>}
{section==="quality"&&<><InspectionForm tasks={data.tasks} busy={busy} submit={call}/><div className="admin-list">{data.inspections.map(item=><Line key={item.id} title={`${item.propertyName} · ${"★".repeat(item.rating??0)}${"☆".repeat(5-(item.rating??0))}`} detail={`${item.inspector} · ${item.remarks||"Sans remarque"} · ${dt(item.createdAt)}`} status={item.status}/>)}</div></>}
{section==="inventory"&&<><InventoryForm data={data} busy={busy} submit={call}/><Table heads={["Maison","Pièce","Équipement","Nombre","Valeur","État"]} rows={data.inventory.map(i=>[i.propertyName,i.room,i.name,String(i.quantity),money(i.valueCents),i.condition])}/></>}
{section==="maintenance"&&<Table heads={["Maison","Incident","Priorité","Responsable","Coût","Statut"]} rows={data.maintenance.map(i=>[i.propertyName,i.title,i.priority,i.assignee||"—",money(i.costCents),i.status])}/>}
{section==="interventions"&&<><InterventionForm data={data} busy={busy} submit={call}/><div className="admin-list">{data.interventions.map(i=><div className="admin-health-row" key={i.id}><div><strong>{i.incidentTitle} · {i.propertyName}</strong><span>{i.assignee||i.provider||"Non attribuée"} · {dt(i.plannedFor)}</span></div><select value={i.status} onChange={e=>void call({action:"update_intervention",interventionId:i.id,status:e.target.value})}>{["planned","assigned","postponed","in_progress","completed","cancelled"].map(s=><option key={s}>{s}</option>)}</select></div>)}</div></>}
{(section==="stock"||section==="consumables")&&<div className="stock-grid">{data.stock.filter(i=>section==="consumables"?i.category==="consumable":i.category!=="consumable").map(i=><article className={i.low?"low-stock":""} key={i.id}><span>{i.propertyName}</span><h3>{i.name}</h3><p>{i.quantity} {i.unit} · seuil {i.threshold}</p><label>Nouveau niveau<input type="number" min="0" defaultValue={i.quantity} onBlur={e=>void call({action:"adjust_stock",stockId:i.id,quantity:Number(e.target.value)})}/></label>{i.low&&<strong>À renouveler : {Math.max(0,i.target-i.quantity)} {i.unit}</strong>}</article>)}</div>}
{section==="photos"&&<div className="admin-callout"><h3>Photothèque opérationnelle privée</h3><p>Le stockage privé « operations » classe les photos avant arrivée, après départ, incident, maintenance et qualité. Les fichiers ne sont jamais publics et restent associés à la maison, au séjour et à la tâche.</p><Table heads={["Maison","Type","Légende","Date"]} rows={data.photos.map(i=>[i.propertyName,i.kind,i.caption,dt(i.takenAt)])}/></div>}
{section==="reports"&&<><div className="admin-kpis"><K l="Temps moyen ménage" v={`${data.metrics.averageCleaningMinutes||"—"} min`}/><K l="Contrôles" v={data.inspections.length}/><K l="Incidents" v={data.maintenance.length}/><K l="Coûts" v={money(data.metrics.maintenanceCostCents)}/></div><p className="admin-note">Les rapports sont calculés depuis les tâches, inspections, incidents, stocks et inventaires enregistrés dans Supabase.</p></>}
</section>;}
function K({l,v}:{l:string;v:string|number}){return <article><span>{l}</span><strong>{v}</strong></article>}function Line({title,detail,status}:{title:string;detail:string;status:string}){return <div className="admin-health-row"><div><strong>{title}</strong><span>{detail}</span></div><span className="admin-status">{status}</span></div>}
function TaskCard({task,busy,submit}:{task:HousekeepingSnapshot["tasks"][number];busy:boolean;submit:(p:Record<string,unknown>)=>Promise<void>}){const update=(checklist:typeof task.checklist,status=task.operationalStatus)=>submit({action:"update_task",taskId:task.id,operationalStatus:status,checklist,offlineRevision:task.offlineRevision});return <article className="housekeeping-task"><div><span>{dt(task.scheduledFor)}</span><h3>{task.propertyName}</h3><strong>{task.operationalStatus}</strong></div><select value={task.operationalStatus} disabled={busy} onChange={e=>void update(task.checklist,e.target.value)}>{["to_prepare","cleaning","quality_control","ready","maintenance","blocked","urgent"].map(s=><option key={s}>{s}</option>)}</select><div className="admin-checklist">{task.checklist.map(i=><label key={i.id}><input type="checkbox" checked={i.done} onChange={()=>void update(task.checklist.map(x=>x.id===i.id?{...x,done:!x.done}:x))}/>{i.label}</label>)}</div><small>{task.assignee||"Non attribué"} · {task.checklist.filter(i=>i.done).length}/{task.checklist.length}</small></article>}
function InspectionForm({tasks,busy,submit}:{tasks:HousekeepingSnapshot["tasks"];busy:boolean;submit:(p:Record<string,unknown>)=>Promise<void>}){return <form className="admin-editor" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void submit({action:"inspect",taskId:f.get("taskId"),inspector:f.get("inspector"),rating:Number(f.get("rating"))||undefined,remarks:f.get("remarks")||undefined,status:f.get("status")})}}><div className="admin-form-grid"><label>Maison<select name="taskId">{tasks.map(t=><option value={t.id} key={t.id}>{t.propertyName} · {dt(t.scheduledFor)}</option>)}</select></label><label>Responsable<input name="inspector" required/></label><label>Évaluation<select name="rating"><option value="5">★★★★★</option><option value="4">★★★★☆</option><option value="3">★★★☆☆</option></select></label><label>Décision<select name="status"><option value="approved">Prêt</option><option value="correction_required">À corriger</option></select></label><label className="wide">Remarque<input name="remarks"/></label></div><button disabled={busy}>Valider le contrôle</button></form>}
function InventoryForm({data,busy,submit}:{data:HousekeepingSnapshot;busy:boolean;submit:(p:Record<string,unknown>)=>Promise<void>}){return <form className="admin-editor" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void submit({action:"create_inventory",propertyId:f.get("propertyId"),room:f.get("room"),category:f.get("category"),name:f.get("name"),quantity:Number(f.get("quantity")),unitValueCents:Math.round(Number(f.get("value"))*100),condition:f.get("condition")})}}><div className="admin-form-grid"><label>Maison<select name="propertyId">{data.properties.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><label>Pièce<input name="room" required/></label><label>Catégorie<input name="category" required/></label><label>Équipement<input name="name" required/></label><label>Nombre<input name="quantity" type="number" min="0" defaultValue="1"/></label><label>Valeur unitaire (€)<input name="value" type="number" min="0" defaultValue="0"/></label><label>État<select name="condition"><option value="new">Neuf</option><option value="good">Bon</option><option value="worn">Usé</option><option value="damaged">Endommagé</option><option value="missing">Manquant</option></select></label></div><button disabled={busy}>Ajouter à l’inventaire</button></form>}
function InterventionForm({data,busy,submit}:{data:HousekeepingSnapshot;busy:boolean;submit:(p:Record<string,unknown>)=>Promise<void>}){return <form className="admin-editor" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void submit({action:"plan_intervention",incidentId:f.get("incidentId"),assignee:f.get("assignee")||undefined,provider:f.get("provider")||undefined,plannedFor:new Date(String(f.get("plannedFor"))).toISOString(),notes:f.get("notes")||undefined})}}><div className="admin-form-grid"><label>Incident<select name="incidentId">{data.maintenance.map(i=><option value={i.id} key={i.id}>{i.propertyName} · {i.title}</option>)}</select></label><label>Responsable<input name="assignee"/></label><label>Prestataire<input name="provider"/></label><label>Date prévue<input name="plannedFor" type="datetime-local" required/></label><label className="wide">Notes<input name="notes"/></label></div><button disabled={busy}>Planifier</button></form>}
function Table({heads,rows}:{heads:string[];rows:string[][]}){return <div className="admin-table-wrap"><table><thead><tr>{heads.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j}>{v}</td>)}</tr>)}</tbody></table></div>}
