"use client";import{FormEvent,useEffect,useMemo,useState}from"react";import type{YieldSnapshot}from"@/platform/yield-management/contracts";
type Section="dashboard"|"recommendations"|"calendar"|"events"|"strategy"|"history";const sections:Record<Section,string>={dashboard:"Dashboard",recommendations:"Recommandations",calendar:"Calendrier tarifaire",events:"Événements",strategy:"Stratégies",history:"Historique"};const money=(c:number)=>new Intl.NumberFormat("fr-FR",{style:"currency",currency:"EUR"}).format(c/100);const date=(v:string)=>new Intl.DateTimeFormat("fr-FR",{dateStyle:"medium"}).format(new Date(`${v.slice(0,10)}T12:00:00Z`));
export function YieldManagementAdmin({token,notify}:{token:string;notify:(v:string)=>void}){const[data,setData]=useState<YieldSnapshot|null>(null);const[section,setSection]=useState<Section>("dashboard");const[busy,setBusy]=useState(false);const[property,setProperty]=useState("");
const call=async(payload?:Record<string,unknown>)=>{setBusy(true);try{const response=await fetch("/api/admin/yield",{method:payload?"POST":"GET",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:payload?JSON.stringify(payload):undefined});const body=await response.json();if(!response.ok)return notify(body.error??"Yield Management indisponible.");if(payload)notify("Décision tarifaire enregistrée et auditée.");const refresh=payload?await fetch("/api/admin/yield",{headers:{Authorization:`Bearer ${token}`}}):response;const snapshot=payload?await refresh.json():body;setData(snapshot);if(!property&&snapshot.strategies?.[0])setProperty(snapshot.strategies[0].propertyId);}finally{setBusy(false);}};useEffect(()=>{void call();},[]);// eslint-disable-line react-hooks/exhaustive-deps
const rows=useMemo(()=>data?.recommendations.filter(item=>!property||item.propertyId===property)??[],[data,property]);if(!data)return <section className="admin-panel"><p>{busy?"Analyse de la demande…":"Données indisponibles."}</p></section>;
return <section className="admin-panel"><div className="admin-panel__heading"><div><p className="eyebrow">Tarification assistée, décision humaine</p><h2>Yield Management</h2></div><div className="admin-actions"><select value={property} onChange={e=>setProperty(e.target.value)}>{data.strategies.map(item=><option value={item.propertyId} key={item.id}>{item.propertyName}</option>)}</select><button type="button" disabled={busy||!property} onClick={()=>void call({action:"generate",propertyId:property,days:90})}>Analyser les 90 prochains jours</button></div></div><nav className="revenue-tabs" aria-label="Yield Management">{(Object.keys(sections)as Section[]).map(id=><button type="button" key={id} aria-current={section===id?"page":undefined} onClick={()=>setSection(id)}>{sections[id]}</button>)}</nav>
{section==="dashboard"&&<><div className="admin-kpis"><K l="À valider" v={data.metrics.pending}/><K l="Acceptées" v={data.metrics.accepted}/><K l="Refusées" v={data.metrics.rejected}/><K l="Variation moyenne" v={`${data.metrics.averageChange>0?"+":""}${data.metrics.averageChange} %`}/><K l="Impact potentiel" v={money(data.metrics.projectedRevenueImpactCents)}/></div><div className="admin-two-columns"><article className="admin-card"><h3>Principales opportunités</h3>{rows.filter(r=>r.status==="pending").sort((a,b)=>Math.abs(b.recommendedRateCents-b.baseRateCents)-Math.abs(a.recommendedRateCents-a.baseRateCents)).slice(0,8).map(r=><Recommendation key={r.id} row={r} busy={busy} call={call}/>)}</article><article className="admin-card"><h3>Principe de sécurité</h3><p>Le moteur propose et explique. Aucun tarif n’est publié tant que Stéphanie ne l’a pas accepté.</p><p>Les planchers, plafonds et variations maximales empêchent les recommandations incohérentes.</p></article></div></>}
{section==="recommendations"&&<div className="yield-list">{rows.filter(r=>r.status==="pending").map(r=><Recommendation key={r.id} row={r} busy={busy} call={call}/>)}</div>}
{section==="calendar"&&<div className="yield-calendar">{rows.map(r=>{const change=Math.round((r.recommendedRateCents/r.baseRateCents-1)*100);return <article key={r.id} className={change>0?"increase":change<0?"decrease":""}><span>{date(r.stayDate)}</span><strong>{money(r.recommendedRateCents)}</strong><small>{money(r.baseRateCents)} · {change>0?"+":""}{change}%</small></article>})}</div>}
{section==="events"&&<div className="admin-table-wrap"><table><thead><tr><th>Événement</th><th>Type</th><th>Période</th><th>Impact</th><th>Source</th></tr></thead><tbody>{data.events.map(e=><tr key={e.id}><td>{e.name}</td><td>{e.kind}</td><td>{e.range}</td><td>{e.impactPercentage>0?"+":""}{e.impactPercentage}%</td><td>{e.source}</td></tr>)}</tbody></table></div>}
{section==="strategy"&&<div className="admin-property-grid">{data.strategies.map(s=><Strategy key={s.id} item={s} busy={busy} call={call}/>)}</div>}
{section==="history"&&<div className="admin-list">{data.logs.map(l=><div className="admin-health-row" key={l.id}><div><strong>{l.action}</strong><span>{l.actor} · {new Date(l.createdAt).toLocaleString("fr-FR")}</span></div></div>)}</div>}
</section>}
function K({l,v}:{l:string;v:string|number}){return <article><span>{l}</span><strong>{v}</strong></article>}
function Recommendation({row,busy,call}:{row:YieldSnapshot["recommendations"][number];busy:boolean;call:(p:Record<string,unknown>)=>Promise<void>}){const change=Math.round((row.recommendedRateCents/row.baseRateCents-1)*100);return <article className="yield-recommendation"><div><span>{row.propertyName} · {date(row.stayDate)}</span><h3>{money(row.baseRateCents)} → {money(row.recommendedRateCents)}</h3><strong>{change>0?"+":""}{change}% · confiance {row.confidence}%</strong></div><ul>{row.factors.map((f,i)=><li key={`${f.code}-${i}`}><strong>{f.label} {f.percentage>0?"+":""}{f.percentage}%</strong><span>{f.explanation}</span></li>)}</ul><div><button disabled={busy} type="button" onClick={()=>void call({action:"decide",recommendationId:row.id,decision:"rejected",note:"Refusée depuis le tableau de bord"})}>Refuser</button><button disabled={busy} type="button" onClick={()=>void call({action:"decide",recommendationId:row.id,decision:"accepted",note:"Validée par Stéphanie"})}>Accepter</button></div></article>}
function Strategy({item,busy,call}:{item:YieldSnapshot["strategies"][number];busy:boolean;call:(p:Record<string,unknown>)=>Promise<void>}){const save=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);void call({action:"update_strategy",strategyId:item.id,minimumRateCents:Math.round(Number(f.get("min"))*100),maximumRateCents:Math.round(Number(f.get("max"))*100),targetOccupancy:Number(f.get("target")),enabled:f.get("enabled")==="on"})};return <form onSubmit={save} className="admin-card"><h3>{item.propertyName}</h3><label>Tarif minimum (€)<input name="min" type="number" defaultValue={item.minimumRateCents/100}/></label><label>Tarif maximum (€)<input name="max" type="number" defaultValue={item.maximumRateCents/100}/></label><label>Occupation cible (%)<input name="target" type="number" min="0" max="100" defaultValue={item.targetOccupancy}/></label><label><input name="enabled" type="checkbox" defaultChecked={item.enabled}/> Stratégie active</label><button disabled={busy}>Enregistrer les garde-fous</button></form>}
